### ISSUE TITLE
Reproductible output

### ISSUE THREAD

**Issue by aviau** [rakyll/statik#13] opened 2015-09-16 18:34 UTC
Hello,

Is there any way to have reproductible output from statik?

As a context, this is needed for Debian. One of the packages I manage (InfluxDB) uses statik and I would like for it to be reproductible.

**Comment by rakyll** [comment] 2015-09-16 18:37
Could you explain in detail what you mean by reproducible output? The generated statik package must be reusable unless the source asset directory is modified.

**Comment by aviau** [comment] 2015-09-16 18:44
Take a look at this [log](https://reproducible.debian.net/rb-pkg/unstable/amd64/influxdb.html).

We have infrastructure that builds all packages in Debian twice and compares the result. If it is not bit-by-bit identical, the build is not reproductible.

As you can see in the log, most of the file is identical. There is only minimal difference. I wonder what this difference comes from.

**Comment by rakyll** [comment] 2015-09-17 20:27
Thanks for the details. It is a bug, I will try to get back on it later today.

**Comment by rakyll** [comment] 2015-09-17 21:15
I am not able to reproduce it against the other assets directories I have. InfluxDB may have a condition that may leading to the problem. Could you report it against the influxdb first or provide a minimal reproducible case?

**Comment by aviau** [comment] 2015-09-29 23:21
I'll take a look at it and report back. Thanks!

**Comment by rakyll** [comment] 2016-03-21 23:32
Closing until it is reproducible.

**Closed by rakyll** 2016-03-21 23:32 UTC

**Comment by aviau** [comment] 2016-07-01 23:27
Sorry for the late response, I don't have much experience on this subject so I put this issue on the bottom of my priority list.

I have found the issue. The Debian CI changes the timestamp of source files when  testing for reproductibility. 

See https://reproducible-builds.org/docs/timestamps

Could statik be updated so that its output is not sensitive to file timestamps?
